name: flutter_661
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  animate_do: ^3.3.4
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  geolocator: ^13.0.2
  cloud_firestore: ^5.6.0
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  easy_debounce: ^2.0.3
  intl: ^0.18.1
  flutter_animate: ^4.5.2
  animations: ^2.0.11
  google_fonts: ^6.2.1
  local_auth: ^2.3.0
  firebase_auth: ^5.4.0
  firebase_messaging: ^15.2.0
  firebase_admin: ^0.3.0
  googleapis_auth: ^1.6.0
  overlay_support: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
